version: 1.0.{build}
image: Visual Studio 2019
install:
  - dotnet tool install -g Cake.Tool --version 0.36.0
build_script:
- cmd: dotnet cake -Target=CI
test: off
cache:
  - tools
  - '%USERPROFILE%\.sonar\cache'
